#!/bin/bash

EXTRA_ARGS="--release"

function help_func() {
	echo """
help		This help text
info		Information about the application and why you either need it or dont

windows		Builds the windows version of pancake-share
linux		Builds the linux version of pancake-share

clean		Cleans the build environment
all			Builds all applicable versions, used internally to build all release binaries
"""
}
function info_func() {
	echo """
Empty for now, the application hasnt even left development. Why are you here?
"""
}
function clean_func() {
	echo Cleaning target/$'\n'
	cargo clean
}

function build_windows() {
	echo Building windows binaries in target/x86_64-pc-windows-gnu/pancake-share.exe$'\n'
	cargo build --target x86_64-pc-windows-gnu --features=windows-os ${EXTRA_ARGS}
}
function build_linux() {
	echo Building linux binaries in target/x86_64-pc-windows-gnu/pancake-share$'\n'
	cargo build --target x86_64-unknown-linux-gnu --features=linux-os ${EXTRA_ARGS}
}
function build_all() {
	build_linux
	build_windows
	EXTRA_ARGS=""
	build_linux
	build_windows
	EXTRA_ARGS="--release"
}

[[ -z $@ ]] && {
	echo Use help subcommand for information about how to use this build tool.
	echo Use info subcommand for general information about this build tool and this project.
	echo Example: ./build help
	echo Example: ./build info
	exit
}

for arg in "$@"
do
	case "$arg" in
	
	windows)
	build_windows
	;;
	
	linux)
	build_linux
	;;
	
	clean)
	clean_func
	;;
	
	help)
	help_func
	;;
	
	-h)
	help_func
	;;
	
	--help)
	help_func
	;;
	
	info)
	info_func
	;;
	
	all)
	build_all
	;;
	
	*)
	echo Invalid input.
	help_func
	exit
	;;
	
	esac
done
